version: '2'
services:
  webtest:
    build: .
    command: bin/ci "npm run watch-tests"
    volumes:
    - .:/usr/app/
    links:
      - postgrestest
    environment:
      DATABASE_URL: postgres://todoapp@postgrestest/todos
  postgrestest:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: todoapp
      POSTGRES_DB: todos
